# Display help information
default:
    @just --list

# pnpm run dev  -- Run development build locally
dev:
    PUBLIC_API_ROOT=http://localhost:3000 pnpm run dev

# pnpm run build  --  Builds for the server, use build-local to build locally
build:
    SK_BASE=/lingtools pnpm run build

# pnpm run build  -- Builds locally
build-local:
    pnpm run build

# Run the built image, using local settings
run-local:
    podman run \
        --name lingtools-client \
        --detach \
        --init \
        --stop-signal=SIGINT \
        --rm \
        -p 5173:3000 \
        --env PUBLIC_API_ROOT=http://localhost:3000 \
        --env ORIGIN=http://localhost:5173 \
        lingtools-client

# Stop the locally running container
stop-local:
    podman stop lingtools-client

# Build the container image using podman (NOTE: Make sure to "build" first)
image:
    podman build -t lingtools-client -f Dockerfile .

# Push the built image to the gtlab container registry
push-labacr:
    podman tag lingtools-client gtlabcontainerregistry.azurecr.io/lingtools-client
    podman push gtlabcontainerregistry.azurecr.io/lingtools-client

# Build And Push -- Runs the commands 'build', 'image' and 'push-labacr' in sequence
bap: build image push-labacr
