location /webpipeline {
    rewrite ^/webpipeline(.*)$ /webpipeline/$1 permanent;
}

location /webpipeline/ {
    proxy_pass http://127.0.0.1:8080/webpipeline/;
}

location /webpipelineapi {
    client_max_body_size 10m;
    rewrite ^/webpipelineapi(.*)$ $1 break;
    proxy_pass http://127.0.0.1:8081;
}
