FROM debian:sid-slim
RUN apt-get update && apt-get install -y libc6 curl
RUN curl https://apertium.projectjj.com/apt/install-nightly.sh | bash
RUN apt-get install -y antiword cg3 hfst
RUN rm -rf /var/lib/apt/lists/*
COPY lookup /usr/local/bin/lookup
COPY target/release/lingtoolapi /usr/local/bin/lingtoolapi
COPY assets /var/assets
WORKDIR /var
CMD ["lingtoolapi"]
